services:
  db:
    image: postgres:16
    container_name: cyber_db
    restart: always
    environment:
      POSTGRES_USER: cyber_admin
      POSTGRES_PASSWORD: dev_password_change_me
      POSTGRES_DB: cyber_awareness
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cyber_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data: